Add bilingual feature
CXZ7720/Shuttle_PWA pull request #67
Opened 2020-11-06 09:32 UTC by talisman6803

## Pull request checklist

**Please check if your PR meets the following requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Tested with (`npm run dev`) and is working great
- [ ] Build tested with (`node build/build.js`) and no errors
- [ ] Double checked the two items above

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring
- [ ] Documentation
- [ ] Other (describe): 

## Describe your Pull Request

Modify ``BigName.vue`` , ``Title.vue`` , ``Target.vue`` for bilingual features.

## Additional content

Due to some sort of commit problem, I did PR again after solving the problem.

2020-11-06 10:07 UTC, Taewan-P requested changes
Changes requested above.

2020-11-06 10:07 UTC, Taewan-P commented on src/components/BigName.vue
> +    <p>{{ this.target }}</p>
This spacebar is unnecessary

2020-11-06 10:07 UTC, Taewan-P commented on src/components/BigName.vue
> +      target: this.getStationName(this.val),
The comma at the end of this line is unnecessary

2020-11-06 10:07 UTC, Taewan-P commented on src/components/BigName.vue
> +    },
The comma at the end of this line is unnecessary too.

2020-11-06 10:07 UTC, Taewan-P commented on src/components/BigName.vue
> +  },
The comma at the end of this line is unnecessary too.

2020-11-06 10:07 UTC, Taewan-P commented on src/components/BigName.vue
> +      } else {
Please use a new line when stating else {} statement.

2020-11-06 10:07 UTC, Taewan-P commented on src/components/Target.vue
> +      <span class="time_num">{{
Why is this element divided in three lines? Please make these in one line.

2020-11-06 10:07 UTC, Taewan-P commented on src/components/Target.vue
> +      }}</span>
Same here.

2020-11-06 10:07 UTC, Taewan-P commented on src/components/Target.vue
> +    },
Unnecessary comma

2020-11-06 10:07 UTC, Taewan-P commented on src/components/Target.vue
> +    },
Unnecessary comma

2020-11-06 10:07 UTC, Taewan-P commented on src/components/Target.vue
> +  },
Unnecessary comma

2020-11-06 10:09 UTC, Taewan-P commented
Please take care of your codes (Indentation, unnecessary codes, etc...) before submitting a PR.

2020-11-11 09:28 UTC, talisman6803 commented
Please check the new commit. I have corrected the upper matters that are mentioned. It was an unintended problem caused by the personal indentation setting of the editor.

2020-11-11 10:35 UTC, Taewan-P approved these changes
LGTM

2020-11-11 10:35 UTC, merged